/**
 * All UI strings used in the app. Each key must have both en and zh values.
 * For interpolated values, use `{key}` placeholders (e.g., "{{count}} model(s)").
 */
const translations = {
  en: {
    app: {
      title: "DeepSeek API Usage Analytics",
      subtitle: "Drop your monthly CSV exports to see usage analytics",
    },
    tabs: {
      overview: "Overview",
      projects: "By Custom Projects",
      keys: "By Key",
      cache: "Cache",
      trends: "Trends",
    },
    header: {
      loadDifferent: "Load different file",
      clear: "Clear",
      sisterProject: "Agnes AI Tool",
      sisterProjectTitle: "Visit the sister Agnes AI usage analyzer",
    },
    footer: {
      text: "Deepseek AI Usage Analytics Dashboard by Gavin & Mindrose Team · Data processed locally in your browser · ",
      version: "Version",
      relatedTools: "Related Tools",
      sisterProject: "Agnes AI Usage Analytics",
      visitSisterRepo: "Agnes Repo",
    },
    dropzone: {
      processing: "Processing CSVs…",
      title: "Drop your DeepSeek CSVs here or click to upload",
      hint: "Drop one or more months — amount-*.csv + cost-*.csv pairs, or a .zip archive",
      privacy:
        "Multiple months are auto-merged · Files stay in your browser — nothing is uploaded",
      oversizedTitle: "File too large",
      oversizedHint:
        'Each file must be under 50 MB. The file "{name}" is {size} MB. Large files may freeze the browser.',
      processingError: "Processing Error",
    },
    kpi: {
      totalCost: "Total Cost",
      totalTokens: "Total Tokens",
      cacheHitRate: "Cache Hit Rate",
      activeKeys: "Active API Keys",
      saved: "{tokens} saved",
      models: "{count} model(s)",
    },
    overview: {
      dailyCost: "Daily Cost",
      costByKey: "Cost by API Key",
    },
    trends: {
      dailyCost: "Daily Cost",
      dailyTokens: "Daily Tokens",
      cacheHitRate: "Cache Hit Rate",
      requestCount: "Request Count",
      heroSubtitle: "Over {days} days",
    },
    cache: {
      hitRateTitle: "Cache Hit Rate",
      servedFromCache: "{tokens} input tokens served from cache",
      dailyHitRate: "Daily Cache Hit Rate",
      hitsVsMisses: "Cache Hits vs Misses by Key",
      noCacheTitle: "No cache usage detected",
      noCacheHint:
        "Enable prompt caching on your DeepSeek API calls to reduce costs.",
      hits: "Cache Hits",
      misses: "Cache Misses",
    },
    keys: {
      title: "Per-Key Breakdown",
      apiKeyName: "API Key Name",
      tokens: "Tokens",
      cost: "Cost",
      cacheHit: "Cache Hit",
      requests: "Requests",
      heroSubtitle: "{keys} key(s) · {models} model(s)",
    },
    error: {
      missingColumns: "CSV schema not recognized",
      malformedRow: "CSV parse error",
      emptyFile: "Empty file",
      incompleteUpload: "Incomplete upload",
      row: "Row",
      column: "Column",
    },
    warning: {
      dateMismatch: "Date mismatch",
      noCostMatch: "No cost data",
      partialCacheData: "Partial cache data",
      schemaDrift: "Schema drift",
    },
    meta: {
      title: "DeepSeek API Usage Analytics Dashboard by Gavin & Mindrose Team",
      description:
        "Visualize your DeepSeek API usage — drop your monthly CSVs and get instant cost analytics, cache analysis, and per-key breakdowns. Free, open source, browser-side.",
    },
    langSwitcher: {
      label: "Language",
    },
    empty: {
      overview: "No data for the selected model. Try a different filter.",
      keys: "No API keys found in the data.",
      trends: "Not enough data to show trends. Upload more months of CSVs.",
      projects: "No data yet. Upload CSVs and configure project groups.",
    },
    theme: {
      light: "Light",
      dark: "Dark",
      switchToDark: "Switch to dark mode",
      switchToLight: "Switch to light mode",
    },
    modelFilter: {
      allModels: "All Models",
    },
    copyToast: {
      copied: "Copied {name} cost",
      clickToCopy: "Click to copy cost",
    },
    share: {
      share: "Share",
      shareTab: "Share This View",
      yourName: "Your / Team Name",
      namePlaceholder: "e.g. Mindrose Team",
      nameHint: 'Displayed as "From XXX" on the image',
      messageLabel: "Message (optional)",
      messagePlaceholder: "e.g. Our team spent ¥12K on DeepSeek API last month, cache hit rate is great!",
      messageHint: "A catchy message makes people more likely to share and discuss",
      generateAndCopy: "Generate & Copy",
      downloadPNG: "Download PNG",
      copiedToast: "Copied! Paste anywhere to share",
      newShare: "New Share",
      from: "From",
      generatedBy: "Generated by DeepSeek Usage Analytics",
      scanToVisit: "Scan to visit",
      dailyAverage: "Daily Average",
      peak: "Peak",
      lowest: "Lowest",
      tokensSaved: "Tokens Saved",
      modalTitle: "Share to Social Media",
      copyFailed: "Copy failed, try download instead",
      clipboardUnsupported: "Clipboard image not supported, downloaded instead",
      generating: "Generating…",
      generateFailed: "Failed to generate image",
      downloadFailed: "Download failed",
    },
    projects: {
      configure: "Configure",
      modalTitle: "Custom Project Configuration",
      projectName: "Project Name",
      addProject: "Add Project",
      removeProject: "Remove",
      save: "Save",
      cancel: "Cancel",
      uncategorized: "Uncategorized",
      heroProjects: "Projects",
      sectionTitle: "By Project",
      columnProject: "Project",
      dragHint: "Drag keys to assign them to projects",
      unassignedKeys: "Unassigned Keys",
      projectKeys: "Project Keys",
      dropHere: "Drop keys here",
      duplicateName: "Project name already exists",
      unsavedChanges: "Discard unsaved changes?",
      discard: "Discard",
      keyboardHint: "Tip: Drag keys to assign, or select a project from the dropdown on each unassigned key (keyboard: Tab to select → Enter to confirm)",
      resetConfig: "Reset All",
      emptyHint: "Click the gear icon to configure custom project groups",
      assignTo: "Assign to…",
    },
    guideline: {
      pageTitle: "User Guide",
      backToHome: "Back to Home",
      viewGuide: "View Full Guide →",
      toc: "Table of Contents",
      footerNote:
        "This document is updated with app releases. For questions or suggestions, please reach out via {githubLink}.",
    },
    changelog: {
      pageTitle: "Changelog",
      backToHome: "Back to Home",
      intro:
        "Track the evolution of the DeepSeek API Usage Analytics Dashboard. Every version is documented below, covering new features, improvements, bug fixes, and dependency changes since the initial v0.1.0 release.",
      added: "Added",
      improved: "Improved",
      fixed: "Fixed",
      dependencies: "Dependencies",
      githubLabel: "GitHub Repository",
      reviewSourceCode: "Review source code →",
      lastUpdated: "Last updated: June 17, 2026",
      viewChangelog: "View Changelog →",
    },
    privacy: {
      pageTitle: "Privacy Policy",
      effectiveDate: "Effective Date: June 13, 2026",
      intro:
        'Your privacy is critically important to us. This Privacy Policy explains how the DeepSeek API Usage Analytics Dashboard ("the App") handles your data.',
      noCollectionTitle: "1. No Data Collection",
      noCollectionDesc:
        "The App is a pure client-side application. All CSV file parsing, cost computation, and chart rendering happen entirely within your browser. We do not collect, store, transmit, or have access to any of the CSV data you upload.",
      localProcessingTitle: "2. Local Processing",
      localProcessingDesc:
        "Your DeepSeek CSV files (amount-*.csv, cost-*.csv) are read and processed exclusively by JavaScript running in your browser. No data is sent to any backend server, database, or third-party service. The App has no server-side component for data handling. Application preferences you configure, such as custom project groupings, are stored only in your browser's local storage and are never transmitted.",
      analyticsTitle: "3. Google Analytics",
      analyticsDesc:
        "We use Google Analytics 4 (GA4) to collect anonymized page-view statistics. This helps us understand how the App is being used so we can improve it. GA4 may use cookies and collect information such as page URLs visited, browser type, and approximate geographic region. No CSV content or usage data from your uploaded files is tracked.",
      analyticsOptOut:
        "You can opt out of Google Analytics tracking by using a browser extension such as Google's opt-out addon, or by configuring your browser to block third-party cookies.",
      gaIdNote:
        "Google Analytics is only active when the environment variable NEXT_PUBLIC_GA_ID is configured. In local development environments, no analytics scripts are loaded.",
      thirdPartyTitle: "4. Third-Party Services",
      thirdPartyDesc:
        "Aside from Google Analytics (when configured), the App does not integrate any other third-party services, SDKs, or tracking scripts. No advertising networks, data brokers, or analytics providers beyond GA4 are used.",
      securityTitle: "5. Security",
      securityDesc:
        "Since all data processing occurs locally, your CSV files are inherently secure — they never leave your device. The App is served over HTTPS to ensure the application code is transmitted securely.",
      changesTitle: "6. Changes to This Policy",
      changesDesc:
        "We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated effective date. We encourage you to review this policy periodically.",
      contactTitle: "7. Contact",
      contactDesc:
        "If you have questions or concerns about this Privacy Policy, please open an issue on our GitHub repository or reach out to the development team.",
      githubLabel: "GitHub Repository",
      reviewSourceCode: "Review source code →",
    },
    terms: {
      pageTitle: "Terms of Use",
      effectiveDate: "Effective Date: June 13, 2026",
      intro:
        'By using the DeepSeek API Usage Analytics Dashboard ("the App"), you agree to these Terms of Use. If you do not agree, please do not use the App.',
      asIsTitle: "1. As-Is Service",
      asIsDesc:
        'The App is provided "as is" and "as available," without warranties of any kind, either express or implied. We do not guarantee that the App will be error-free, uninterrupted, or suitable for your specific needs.',
      noWarrantyTitle: "2. No Warranty",
      noWarrantyDesc:
        "To the fullest extent permitted by law, we disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Use of the App is at your own risk.",
      notAffiliatedTitle: "3. Not Affiliated with DeepSeek",
      notAffiliatedDesc:
        "This App is an independent, open-source project developed by Gavin Chen and the MindRose team. It is not affiliated with, endorsed by, or sponsored by DeepSeek (深度求索). All DeepSeek-related trademarks belong to their respective owners.",
      userDataTitle: "4. User Data & Responsibility",
      userDataDesc:
        "The App processes CSV data entirely in your browser. You are solely responsible for the data you upload and any decisions made based on the analytics results. We do not store, transmit, or have access to your data, and we bear no responsibility for any inaccuracies in the displayed analytics.",
      openSourceTitle: "5. Open Source",
      openSourceDesc:
        "The App is open source software released under the MIT License. You are free to review, modify, and distribute the source code in accordance with the license terms. The source code is available on GitHub.",
      openSourceLicense:
        "Full license text: MIT License — see the LICENSE file in the project repository.",
      limitationTitle: "6. Limitation of Liability",
      limitationDesc:
        "In no event shall the developers or contributors be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of or inability to use the App, even if advised of the possibility of such damages. This includes, but is not limited to, damages for errors, omissions, service interruptions, or financial losses.",
      changesTitle: "7. Changes to These Terms",
      changesDesc:
        "We reserve the right to modify these Terms of Use at any time. Changes will be posted on this page with an updated effective date. Continued use of the App after changes constitutes acceptance of the revised terms.",
      contactTitle: "8. Contact",
      contactDesc:
        "If you have questions about these Terms of Use, please open an issue on our GitHub repository or reach out to the development team.",
      githubLabel: "GitHub Repository",
      reviewSourceCode: "Review source code →",
    },
    blog: {
      pageTitle: "Blog",
      ctaTitle: "Try our free DeepSeek API Usage Dashboard",
      ctaDesc: "Drag your CSVs, see your costs. 100% private, no signup.",
      ctaButton: "Open Dashboard",
    },
    author: {
      pageTitle: "Author & Team",
      pageSubtitle:
        "Background, authorship, and public identity signals for the DeepSeek API Usage Analytics Dashboard project.",
      intro:
        "The Mindrose team is composed of members with diverse backgrounds, coming from various major tech companies, with extensive experience in software architecture, business analysis, online marketing, SEO & GEO, and more.",
      profileTitle: "Author Profile",
      profileName: "Gavin Chen",
      profileRole: "Solution Architect & Developer",
      profileDesc:
        "Gavin Chen leads product direction, technical implementation, and content strategy for this project, working together with the MindRose team on product delivery, marketing, and maintenance.",
      verificationTitle: "Public Profiles & Verification",
      teamMembersTitle: "Team Members",
      teamMembersDesc:
        "Meet the core contributors and specialists behind the MindRose team, who drive the continuous evolution of our products.",
      member1Name: "Gavin Chen",
      member1Role: "Business Analyst & System Architect",
      member1Desc:
        "An architect with years of BA experience, focusing on business requirements, product strategy, and system architecture (and development).",
      member2Name: "Lindsay Lin",
      member2Role: "SEO & International Trade Specialist",
      member2Desc:
        "Familiar with cross-border product marketing strategies and highly experienced in hands-on SEO, leading our SEO & GEO strategies.",
      member3Name: "Angela Lee",
      member3Role: "Online Marketing Specialist",
      member3Desc:
        "Expert in online marketing strategies, content creation, and analysis, helping products and services succeed in digital marketing and promotion.",
      member4Name: "Simon L.",
      member4Role: "Backend & DevOps Engineer",
      member4Desc:
        "Leads various server architecture designs, database optimizations, and cloud-native deployments.",
      githubLabel: "Project GitHub Repository",
      linkedInLabel: "Gavin's LinkedIn",
      websiteLabel: "MindRose Website",
    },
    blogIndex: {
      pageTitle: "Blog: How We Grow with DeepSeek Faster, Better, and Smarter",
      pageSubtitle:
        "Deep dives into DeepSeek API use cases, cost optimization, context caching strategies, pricing comparisons, and developer tools — original content from the MindRose team.",
      article1Title:
        "The Ultimate Guide to DeepSeek API Context Caching (2026)",
      article1Desc:
        "Learn how DeepSeek's prefix-matching disk caching works, why your cache hit rate might be lower than expected, and 5 prompt engineering techniques to maximize savings.",
      article1Tags: "Caching, Cost Optimization, DeepSeek, Token Cost",
      article2Title:
        "Top 5 DeepSeek API Cost Optimization & Observability Tools",
      article2Desc:
        "A comprehensive comparison of the best tools for monitoring and optimizing DeepSeek API costs — from real-time observability platforms to privacy-first CSV analyzers.",
      article2Tags: "Tools, Comparison, Cost Optimization, DeepSeek, Token Cost",
      article3Title:
        "OpenAI GPT vs Claude vs DeepSeek V4 Pro: A Developer's Cost-Benefit Analysis",
      article3Desc:
        "Hard numbers on API pricing differences — input costs can differ by 270×. We break down when each model makes economic sense and how to migrate smoothly.",
      article3Tags: "Comparison, Pricing, OpenAI, Claude, GPT, Anthropic",
    },
    costTracker: {
      pageTitle: "DeepSeek API Cost Tracker",
      badge: "Free Tool",
      heroTitle: "Track Every Cent of Your DeepSeek API Spend",
      heroDesc:
        "Drop your DeepSeek billing CSVs and get instant cost breakdowns by day, model, and API key — all processed locally in your browser. No signup, no server upload.",
      cta: "Analyze My Costs Now",
      privacyBadge: "100% Private — data never leaves your browser",
      feature1Title: "Daily Cost Breakdown",
      feature1Desc:
        "See exactly how much you spent each day with an interactive bar chart. Spot anomalies and spending spikes at a glance.",
      feature2Title: "Per-Key Cost Attribution",
      feature2Desc:
        "Know which API key is burning through your budget. Detailed per-key tables with inline usage bars and copy-to-clipboard support.",
      feature3Title: "Cache Hit Rate Monitoring",
      feature3Desc:
        "Understand how much you save through context caching. Green/amber/red color coding makes it easy to spot low-hanging optimization opportunities.",
      feature4Title: "Multi-Month Comparison",
      feature4Desc:
        "Drag multiple ZIP files at once and they auto-pair by month. Compare spending trends across billing cycles to track your optimization progress.",
      bottomCTA: "Ready to take control of your API costs?",
      bottomCTADesc:
        "No account needed. No data leaves your browser. Just drag, drop, and discover where your tokens go.",
      recommendedTools: "Recommended Tools",
      recommendedDesc:
        "Looking for real-time API observability? These tools complement our CSV-based analyzer:",
      recommendedUsingTools: "Recommended Tools We ARE USING",
      recommendedUsingDes:
        "We are using these tools ourselves for Development / Deployment. Check out for more details.",
        useCasesTitle: "Real Usage Scenarios",
      useCase1Title: "Finance or ops review",
      useCase1Desc:
        "Upload the monthly export before invoice review. The dashboard highlights daily spikes, zero-cost anomalies, and which keys drove the change.",
      useCase2Title: "Client or project chargeback",
      useCase2Desc:
        "If one DeepSeek account serves multiple apps or customers, use the per-key and custom-project views to map spending back to each internal owner.",
      useCase3Title: "Optimization rollback checks",
      useCase3Desc:
        "After changing prompts, routing rules, or cache settings, compare multiple months side by side to verify whether the optimization actually reduced spend.",
      comparisonTitle: "When This Tool Fits Best",
      comparisonDesc:
        "This page is best for teams that already export monthly billing CSVs and want a fast answer without setting up an always-on observability stack.",
      comparisonHeaderTool: "Option",
      comparisonHeaderBestFor: "Best for",
      comparisonHeaderTradeoff: "Trade-off",
      comparisonRow1Label: "This CSV analyzer",
      comparisonRow1BestFor:
        "Fast monthly cost reviews, privacy-sensitive teams, zero setup",
      comparisonRow1Tradeoff:
        "Not real-time; works on exported billing files",
      comparisonRow2Label: "API gateway / observability",
      comparisonRow2BestFor:
        "Live request monitoring, alerts, prompt tracing, team workflows",
      comparisonRow2Tradeoff:
        "Usually requires proxy routing, vendor setup, and ongoing cost",
      comparisonRow3Label: "Manual spreadsheets",
      comparisonRow3BestFor:
        "Ad-hoc checks when the team is very small and the data is simple",
      comparisonRow3Tradeoff:
        "Hard to maintain, weak cache visibility, error-prone over time",
      faqTitle: "Cost Tracking FAQ",
      faq1Q: "Why use a CSV cost tracker if I already have the DeepSeek billing page?",
      faq1A:
        "DeepSeek's billing view is useful for raw exports, but this tool restructures the data into daily trends, per-key attribution, cache hit visibility, and project-level summaries.",
      faq2Q: "Who should review this page every month?",
      faq2A:
        "Usually the engineer who owns prompts, the team lead who tracks burn, or the operations person who reconciles invoice deltas. The page is meant for those handoff moments.",
      faq3Q: "Can I use it for post-optimization proof?",
      faq3A:
        "Yes. Upload two or more months and compare daily and per-key changes. That makes it easier to tell whether a prompt rewrite or caching improvement actually reduced cost.",
      backToHome: "Back to Home",
    },
    cacheAnalyzer: {
      pageTitle: "DeepSeek Cache Hit Rate Analyzer",
      badge: "Free Tool",
      heroTitle: "Maximize Your DeepSeek Cache Hit Rate",
      heroDesc:
        "DeepSeek context caching can slash your API costs by up to 90% — but only if you know your hit rate. Upload your CSVs and get a crystal-clear picture of cache performance.",
      cta: "Analyze My Cache Performance",
      privacyBadge: "100% Private — data never leaves your browser",
      cachingExplainerTitle: "How DeepSeek Context Caching Works",
      cachingExplainerDesc:
        "DeepSeek uses prefix matching for its disk caching. If the beginning of your prompt (the prefix) stays the same across requests, subsequent calls reuse the cached computation — dramatically reducing costs. The longer your cached prefix relative to total input, the more you save.",
      cachingTip1Title: "Keep system prompts fixed",
      cachingTip1Desc:
        "Place static instructions at the beginning of every request. DeepSeek caches prompts starting from the first token; changing anything at the front invalidates the entire cache.",
      cachingTip2Title: "Put dynamic content last",
      cachingTip2Desc:
        "Structure your prompts so that user queries, timestamps, and other variable content appear after the fixed system prompt and context. This maximizes the reusable prefix length.",
      cachingTip3Title: "Monitor with our tool",
      cachingTip3Desc:
        "Our cache hit rate chart shows daily trends and per-key stacked bars. A hit rate above 40% (green) means good caching; below 20% (red) means there's room for prompt engineering improvements.",
      feature1Title: "Daily Cache Trend Line",
      feature1Desc:
        "Track your cache hit rate over time. Did a prompt change tank your rate? The trend line tells the story.",
      feature2Title: "Per-Key Hits vs Misses",
      feature2Desc:
        "Stacked bar chart for each API key shows exactly how many tokens were cache hits (green) vs misses (gray), with percentage labels and tooltips.",
      benchmarkTitle: "Practical Hit Rate Benchmarks",
      benchmarkDesc:
        "Exact results vary by workload, but these operating bands are a useful way to judge whether your prompt structure is leaving savings on the table.",
      benchmark1Title: "Below 20%",
      benchmark1Desc:
        "Usually means the stable prefix is too short, or variable content appears too early in the prompt.",
      benchmark2Title: "20% - 40%",
      benchmark2Desc:
        "A workable baseline for mixed workloads. You are getting some reuse, but prompt ordering likely still has room to improve.",
      benchmark3Title: "40% - 60%",
      benchmark3Desc:
        "A strong result for many production teams. Static instructions and reusable context are likely structured reasonably well.",
      benchmark4Title: "60%+",
      benchmark4Desc:
        "Excellent for repetitive workflows such as customer support, templated extraction, or fixed system prompts with small user deltas.",
      strategyTitle: "Additional Optimization Strategies",
      strategy1Title: "Separate stable context from user input",
      strategy1Desc:
        "Keep long-lived knowledge, policy blocks, and tool instructions in a reusable prefix. Append user-specific data after that block.",
      strategy2Title: "Version prompts deliberately",
      strategy2Desc:
        "Small edits to the beginning of the prompt can reset your cache economics overnight. Treat prompt revisions like code releases and watch the hit-rate trend after each change.",
      strategy3Title: "Group similar traffic paths",
      strategy3Desc:
        "If multiple products share the same assistant logic, align their prompt scaffolding so the reusable prefix stays identical across requests.",
      diagnosisTitle: "What to Check When the Rate Drops",
      diagnosis1Title: "Prompt templates changed",
      diagnosis1Desc:
        "A new prefix, reordered instructions, or inserted timestamp near the front can collapse hit rate even when the user experience looks unchanged.",
      diagnosis2Title: "Traffic mix shifted",
      diagnosis2Desc:
        "A sudden increase in one-off tasks, long-tail queries, or new products can reduce prefix reuse without any code regression.",
      diagnosis3Title: "Cache-friendly requests are not routed consistently",
      diagnosis3Desc:
        "If logically similar requests hit different models, keys, or prompt wrappers, the reusable prefix can fragment and dilute the overall rate.",
      bottomCTATitle: "Need help optimizing your prompts for caching?",
      bottomCTADesc:
        "The MindRose team specializes in LLM architecture and prompt engineering. We can help you redesign your system for maximum cache efficiency.",
      bottomCTALink: "Let's talk →",
      backToHome: "Back to Home",
    },
    pricingCalculator: {
      pageTitle: "DeepSeek API Pricing Calculator",
      badge: "Free Tool",
      heroTitle: "Estimate Your DeepSeek API Costs Instantly",
      heroDesc:
        "Compare DeepSeek V4 Flash, V4 Pro, and competitor model pricing. Adjust input/output token counts and cache hit rate assumptions to see real cost projections.",
      currencyCNY: "CNY",
      currencyUSD: "USD",
      inputTokensLabel: "Monthly Input Tokens",
      outputTokensLabel: "Monthly Output Tokens",
      cacheHitRateLabel: "Cache Hit Rate (%)",
      cacheHitRateHint: "Higher hit rate = lower cost. DeepSeek caches at 12.5% of the original input price for hits.",
      costEstimateTitle: "Estimated Monthly Cost",
      deepseekV4Flash: "DeepSeek V4 Flash",
      deepseekV4Pro: "DeepSeek V4 Pro",
      competitorComparison: "Competitor Pricing Comparison",
      comparisonNote:
        "Based on published API pricing as of July 2026. Actual costs may vary based on usage patterns and caching efficiency.",
      compModelHeader: "Model",
      compInputPriceHeader: "Input / 1M tokens",
      compOutputPriceHeader: "Output / 1M tokens",
      compCacheHitHeader: "Cache Hit / 1M tokens",
      compNotesHeader: "Notes",
      compDeepseekV4Flash: "DeepSeek V4 Flash",
      compDeepseekV4Pro: "DeepSeek V4 Pro",
      estimationGuideTitle: "How to Estimate Monthly Usage",
      estimationGuideDesc:
        "If you do not already have billing exports, start from product traffic: requests per day, average prompt size, average response length, and expected cache reuse.",
      estimateStep1Title: "1. Estimate request volume",
      estimateStep1Desc:
        "Count how many requests your app will send in a normal day, then multiply by 30. Separate peak campaigns from baseline traffic.",
      estimateStep2Title: "2. Estimate prompt and response size",
      estimateStep2Desc:
        "Use a few representative prompts to approximate average input and output tokens. For rough planning, consistency matters more than absolute precision.",
      estimateStep3Title: "3. Add a cache assumption",
      estimateStep3Desc:
        "If your system prompt and context are reused heavily, model a higher hit rate. If every request is unique, start closer to 0% and treat savings as upside.",
      billingModelTitle: "How the Billing Model Works",
      billingModelInputTitle: "Uncached input tokens",
      billingModelInputDesc:
        "These are charged at the model's standard input rate. Large prompts dominate cost when the cache hit rate is low.",
      billingModelCacheTitle: "Cached input tokens",
      billingModelCacheDesc:
        "When the prefix matches a previous request, DeepSeek charges the reduced cache-hit price instead of the full input rate.",
      billingModelOutputTitle: "Output tokens",
      billingModelOutputDesc:
        "Generated tokens are billed separately and can become the main cost driver in agentic or reasoning-heavy workflows.",
      resultGuideTitle: "How to Read the Result",
      resultGuide1Title: "Use Flash for high-volume routine work",
      resultGuide1Desc:
        "If the workload is repetitive and latency-sensitive, DeepSeek V4 Flash usually sets the floor for cost planning.",
      resultGuide2Title: "Use Pro when quality offsets the delta",
      resultGuide2Desc:
        "The real question is not whether Pro is more expensive, but whether it cuts retries, human review, or downstream errors enough to justify the gap.",
      resultGuide3Title: "Compare competitors with your actual mix",
      resultGuide3Desc:
        "A model that looks expensive on list price can still make sense for narrow tasks. Re-run the calculator with your own token mix before locking the stack.",
      deployCTA: "Ready to deploy your AI stack?",
      deployCTADesc:
        "Get free cloud credits to run your AI workloads. Vultr offers $100 credit for new users — enough to host your LLM proxy or analytics pipeline.",
      deployCTALink: "Get Vultr Free Credit ($100)",
      backToHome: "Back to Home",
    },
    landing: {
      howItWorksTitle: "How It Works",
      howItWorksStep1Title: "1. Export Data",
      howItWorksStep1Desc:
        "Go to DeepSeek Platform → Usage → Export monthly data. Each month downloads as a ZIP containing amount and cost CSVs.",
      howItWorksStep2Title: "2. Drag & Drop",
      howItWorksStep2Desc:
        "Drag your ZIP files (or extracted CSVs) onto this page. Multiple months are automatically paired and merged.",
      howItWorksStep3Title: "3. View Analytics",
      howItWorksStep3Desc:
        "Instantly see cost charts, per-key breakdowns, cache hit analysis, usage trends, and custom project groupings — all processed locally in your browser.",
      qaTitle: "Frequently Asked Questions",
      qaQ1: "Is my data uploaded to any server?",
      qaA1: "No. All CSV parsing and cost computation runs entirely in your browser. Your data never leaves your device.",
      qaQ2: "What files do I need to upload?",
      qaA2: "You can drag the ZIP archive downloaded from the DeepSeek Platform directly — no extraction needed. Or you can extract and upload the amount-*.csv and cost-*.csv files manually.",
      qaQ3: "Can I analyze multiple months at once?",
      qaA3: "Yes. Drag all your monthly ZIP (or CSV) files at once — they will be automatically paired by filename and concatenated.",
      qaQ4: "What models are supported?",
      qaA4: "Any model listed in your DeepSeek exports. The dashboard auto-detects all models and provides a filter to view them individually or combined.",
      qaQ5: "Why does my cost show as $0?",
      qaA5: "You need to upload both the amount CSV and the cost CSV for the same month. If either file is missing, cost data cannot be calculated.",
      qaQ6: 'What does "Incomplete Upload" mean?',
      qaA6: "It means a month has only the amount file or only the cost file — not both. Add the missing file and re-upload to resolve this.",
      qaQ7: "Where can I find more troubleshooting help?",
      qaA7: "Check the Troubleshooting section in our full User Guide. It covers common issues like CSV format errors, cache configuration, file naming conventions, and more.",
      qaQ8: "Is there a file size limit?",
      qaA8: "Yes, each file must be under 50 MB. This prevents malicious ZIP bombs from freezing your browser. DeepSeek monthly usage exports are typically under 1 MB, so this limit should never be an issue for normal use.",
      qaQ9: "Can I group API keys by custom projects?",
      qaA9: "Yes. Switch to the 'By Custom Projects' tab and click the gear icon to open the configuration panel. Drag API key names from the unassigned pool into your custom project groups. Your project configuration is saved in your browser's local storage.",
      sisterBadge: "Sister Project",
      sisterTitle: "Also using Agnes AI API?",
      sisterDesc:
        "Open the dedicated Agnes AI usage analyzer to review token spend, model distribution, and trends with a matching browser-side workflow.",
      sisterVisit: "Open Agnes AI Analyzer",
      sisterRepo: "View GitHub Repo",
      aboutSectionTitle: "About",
      aboutWhyTitle: "Why We Built This",
      aboutWhyDesc:
        'As our DeepSeek API calls surged, we found the official CSV billing exports nearly impossible to read at a glance. To answer questions like "which project consumed the most tokens?" and "what is our real cache hit rate?", we built our own simple, intuitive, and absolutely secure visualization dashboard.',
      aboutPrivacyTitle: "Under the Hood: Privacy & Tech",
      aboutPrivacyDesc:
        "When handling billing data, privacy is non-negotiable. That's why we chose a pure frontend architecture. Built with Next.js 16 (App Router) and React 19, powered by Papa Parse and ECharts, all CSV parsing and chart rendering happens 100% locally in your browser. No backend server, no database — your data never leaves your device. With Apple-inspired minimalist design and CSS custom property-driven dual themes, we aim to deliver the most elegant data analytics experience.",
      aboutMindRoseTitle: "About MindRose",
      aboutMindRoseDesc:
        'This project is open-sourced by Gavin Chen and the MindRose team. MindRose is a tech team focused on delivering lightweight digital solutions for small and medium manufacturers, logistics companies, and cross-border traders. We don\'t sell vague "digital transformation" concepts — we use AI and full-stack agile development (Next.js, React, Mendix, etc.) to deliver applications that solve real business pain points within weeks. From SEO-optimized independent e-commerce sites, to agile internal system builds, to AI agent workflow integration — we understand tech, and more importantly, we understand your business.',
      aboutContactTitle: "Let's Work Together",
      aboutContactDesc:
        "Looking to build a custom data dashboard for your business? Need deep AI integration into your workflows? Want modern, elegant UI/UX? Need cross-department, multi-terminal business systems? Or interested in collaborating on this open-source project?",
      aboutContactService:
        "We offer professional bottleneck diagnosis, transformation analysis, tailored business solutions, and AI-powered development and operations.",
      aboutContactCTA: "Get in touch:",
      aboutGitHubLabel: "Project GitHub Repo",
      aboutLinkedInLabel: "Gavin's LinkedIn",
      aboutMindRoseLabel: "MindRose Team",
    },
  },

  zh: {
    app: {
      title: "DeepSeek API 用量分析",
      subtitle: "拖拽月度 CSV 文件即可查看用量分析",
    },
    tabs: {
      overview: "总览",
      projects: "按自定义项目",
      keys: "按 Key",
      cache: "缓存",
      trends: "趋势",
    },
    header: {
      loadDifferent: "加载其他文件",
      clear: "清除",
      sisterProject: "Agnes AI 工具",
      sisterProjectTitle: "前往姊妹项目 Agnes AI 用量分析器",
    },
    footer: {
      text: "DeepSeek API 用量分析仪表盘 · 数据仅在浏览器本地处理 · ",
      version: "版本",
      relatedTools: "姊妹工具",
      sisterProject: "Agnes AI 用量分析器",
      visitSisterRepo: "Agnes AI 仓库",
    },
    dropzone: {
      processing: "正在处理 CSV…",
      title: "拖拽 DeepSeek CSV 文件到此处或点击上传",
      hint: "拖拽一个或多个月份 — amount-*.csv + cost-*.csv 文件对，或 .zip 压缩包",
      privacy: "多月份自动合并 · 文件仅存储在浏览器中 — 不会上传",
      oversizedTitle: "文件过大",
      oversizedHint:
        '文件过大：文件 "{name}" 大小为 {size} MB。单个文件不能超过 50 MB，过大的文件可能导致浏览器卡死。',
      processingError: "处理错误",
    },
    kpi: {
      totalCost: "总费用",
      totalTokens: "总 Token 数",
      cacheHitRate: "缓存命中率",
      activeKeys: "活跃 API Key",
      saved: "节省 {tokens}",
      models: "{count} 个模型",
    },
    overview: {
      dailyCost: "每日费用",
      costByKey: "各 Key 费用分布",
    },
    trends: {
      dailyCost: "每日费用",
      dailyTokens: "每日 Token",
      cacheHitRate: "缓存命中率",
      requestCount: "请求次数",
      heroSubtitle: "共 {days} 天",
    },
    cache: {
      hitRateTitle: "缓存命中率",
      servedFromCache: "{tokens} 个输入 token 由缓存提供",
      dailyHitRate: "每日缓存命中率",
      hitsVsMisses: "各 Key 缓存命中 / 未命中",
      noCacheTitle: "未检测到缓存使用",
      noCacheHint: "在 DeepSeek API 调用中启用提示缓存以降低费用。",
      hits: "缓存命中",
      misses: "缓存未命中",
    },
    keys: {
      title: "各 Key 详情",
      apiKeyName: "API Key 名称",
      tokens: "Token 数",
      cost: "费用",
      cacheHit: "缓存命中",
      requests: "请求数",
      heroSubtitle: "{keys} 个 Key · {models} 个模型",
    },
    error: {
      missingColumns: "CSV 格式无法识别",
      malformedRow: "CSV 解析错误",
      emptyFile: "空文件",
      incompleteUpload: "上传不完整",
      row: "行",
      column: "列",
    },
    warning: {
      dateMismatch: "日期不匹配",
      noCostMatch: "缺少费用数据",
      partialCacheData: "缓存数据不完整",
      schemaDrift: "数据结构不一致",
    },
    meta: {
      title: "DeepSeek API 用量分析仪表盘",
      description:
        "可视化您的 DeepSeek API 使用情况 — 拖拽月度 CSV，即时获取费用分析、缓存分析和各 Key 用量明细。数据 100% 本地处理，不上传任何服务器。免费、开源，由 Gavin Chen 和 MindRose 团队维护。",
    },
    langSwitcher: {
      label: "语言",
    },
    empty: {
      overview: "所选模型暂无数据，请尝试切换筛选条件。",
      keys: "未找到 API Key 数据。",
      trends: "数据不足，无法显示趋势。请上传更多月份的 CSV。",
      projects: "暂无数据。请上传 CSV 并配置项目分组。",
    },
    theme: {
      light: "浅色",
      dark: "深色",
      switchToDark: "切换至深色模式",
      switchToLight: "切换至浅色模式",
    },
    modelFilter: {
      allModels: "全部模型",
    },
    copyToast: {
      copied: "已复制 {name} 费用",
      clickToCopy: "点击复制费用",
    },
    share: {
      share: "分享",
      shareTab: "分享此视图",
      yourName: "你的名字 / 团队名字",
      namePlaceholder: "例如：Mindrose 团队",
      nameHint: '图片上会以大号字体显示 "From XXX"',
      messageLabel: "自定义文案（可选）",
      messagePlaceholder: "例如：我们团队上个月 DeepSeek API 花了 ¥12K，缓存命中率还不错！",
      messageHint: "写一句传播语，大家更愿意转发和讨论",
      generateAndCopy: "生成并复制",
      downloadPNG: "下载 PNG",
      copiedToast: "已复制！去微信/飞书/钉钉粘贴即可",
      newShare: "重新生成",
      from: "From",
      generatedBy: "由 DeepSeek Usage Analytics 生成",
      scanToVisit: "扫码访问",
      dailyAverage: "日均",
      peak: "峰值",
      lowest: "最低",
      tokensSaved: "节省 Token",
      modalTitle: "分享到社交媒体",
      copyFailed: "复制失败，请尝试下载",
      clipboardUnsupported: "浏览器不支持剪贴板图片，已自动下载",
      generating: "生成中…",
      generateFailed: "图片生成失败",
      downloadFailed: "下载失败",
    },
    projects: {
      configure: "配置",
      modalTitle: "自定义项目配置",
      projectName: "项目名称",
      addProject: "添加项目",
      removeProject: "移除",
      save: "保存",
      cancel: "取消",
      uncategorized: "未分类",
      heroProjects: "个项目",
      sectionTitle: "按项目",
      columnProject: "项目",
      dragHint: "拖拽 Key 分配到对应项目",
      unassignedKeys: "未分配 Key",
      projectKeys: "项目 Key",
      dropHere: "拖拽 Key 到此处",
      duplicateName: "项目名称已存在",
      unsavedChanges: "放弃未保存的修改？",
      discard: "放弃",
      keyboardHint: "提示：拖拽 Key 分配项目，或使用未分配 Key 旁的下拉菜单通过键盘操作（Tab 选择 → Enter 确认）",
      resetConfig: "全部重置",
      emptyHint: "点击齿轮图标配置自定义项目分组",
      assignTo: "分配到…",
    },
    guideline: {
      pageTitle: "用户操作手册",
      backToHome: "返回首页",
      viewGuide: "查看完整操作指南 →",
      toc: "目录",
      footerNote:
        "文档随应用版本迭代更新。如有疑问或建议，欢迎通过 {githubLink} 反馈。",
    },
    changelog: {
      pageTitle: "更新日志",
      backToHome: "返回首页",
      intro:
        "追踪 DeepSeek API 用量分析仪表盘的演进历程。自 v0.1.0 初始版本以来，每个版本的新增功能、改进优化、问题修复和依赖变更均记录如下。",
      added: "新增",
      improved: "改进",
      fixed: "修复",
      dependencies: "依赖变更",
      githubLabel: "GitHub 仓库",
      reviewSourceCode: "查看源码验证 →",
      lastUpdated: "最后更新：2026 年 6 月 17 日",
      viewChangelog: "查看更新日志 →",
    },
    privacy: {
      pageTitle: "隐私政策",
      effectiveDate: "生效日期：2026 年 6 月 13 日",
      intro:
        "您的隐私对我们至关重要。本隐私政策说明了 DeepSeek API 用量分析仪表盘（以下简称“本应用”）如何处理您的数据。",
      noCollectionTitle: "1. 不收集数据",
      noCollectionDesc:
        "本应用是纯客户端应用。所有 CSV 文件解析、费用计算和图表渲染都在您的浏览器内完成。我们不会收集、存储、传输或访问您上传的任何 CSV 数据。",
      localProcessingTitle: "2. 本地处理",
      localProcessingDesc:
        "您的 DeepSeek CSV 文件（amount-*.csv、cost-*.csv）仅由浏览器中运行的 JavaScript 读取和处理。任何数据都不会发送到后台服务器、数据库或第三方服务。本应用没有用于数据处理的服务器端组件。您配置的应用程序偏好设置（如自定义项目分组）仅保存在浏览器的本地存储中，不会向外传输。",
      analyticsTitle: "3. Google Analytics（谷歌分析）",
      analyticsDesc:
        "我们使用 Google Analytics 4（GA4）收集匿名的页面访问统计数据，以了解应用的使用情况并持续改进。GA4 可能会使用 Cookie 并收集页面 URL、浏览器类型和大致地理位置等信息。您上传的 CSV 内容和使用数据不会被跟踪。",
      analyticsOptOut:
        "您可以通过安装浏览器的 Google 选择退出插件，或将浏览器配置为阻止第三方 Cookie，来选择退出 Google Analytics 跟踪。",
      gaIdNote:
        "Google Analytics 仅在环境变量 NEXT_PUBLIC_GA_ID 已配置时激活。在本地开发环境中，不会加载任何分析脚本。",
      thirdPartyTitle: "4. 第三方服务",
      thirdPartyDesc:
        "除 Google Analytics（已配置时）外，本应用不集成任何其他第三方服务、SDK 或跟踪脚本。不使用广告网络、数据代理或 GA4 之外的任何分析服务。",
      securityTitle: "5. 安全性",
      securityDesc:
        "由于所有数据处理均在本地进行，您的 CSV 文件本质上是安全的——它们永远不会离开您的设备。本应用通过 HTTPS 提供服务，确保应用代码安全传输。",
      changesTitle: "6. 政策变更",
      changesDesc:
        "我们可能会不时更新本隐私政策。变更将在本页面发布，并附上更新后的生效日期。我们建议您定期查看本政策。",
      contactTitle: "7. 联系我们",
      contactDesc:
        "如果您对本隐私政策有任何疑问或疑虑，请在我们的 GitHub 仓库提交 Issue，或联系开发团队。",
      githubLabel: "GitHub 仓库",
      reviewSourceCode: "查看源码验证 →",
    },
    terms: {
      pageTitle: "使用条款",
      effectiveDate: "生效日期：2026 年 6 月 13 日",
      intro:
        "使用 DeepSeek API 用量分析仪表盘（以下简称“本应用”）即表示您同意本使用条款。如果您不同意，请勿使用本应用。",
      asIsTitle: "1. 按现状提供",
      asIsDesc:
        "本应用按“现状”和“可用”状态提供，不作任何明示或暗示的保证。我们不保证本应用无错误、不中断或适用于您的特定需求。",
      noWarrantyTitle: "2. 免责声明",
      noWarrantyDesc:
        "在法律允许的最大范围内，我们不承担所有保证，包括但不限于适销性、特定用途适用性和非侵权的默示保证。使用本应用的风险由您自行承担。",
      notAffiliatedTitle: "3. 与 DeepSeek 无关",
      notAffiliatedDesc:
        "本应用是由 Gavin Chen 和 MindRose 团队开发的独立开源项目。与 DeepSeek（深度求索）无任何关联、认可或赞助关系。所有 DeepSeek 相关商标归其各自所有者所有。",
      userDataTitle: "4. 用户数据与责任",
      userDataDesc:
        "本应用在您的浏览器中处理 CSV 数据。您对上传的数据以及基于分析结果做出的任何决策负全部责任。我们不存储、传输或访问您的数据，对于分析结果的任何不准确性不承担任何责任。",
      openSourceTitle: "5. 开源许可",
      openSourceDesc:
        "本应用是基于 MIT License 发布的开源软件。您可以自由查看、修改和分发源代码，但需遵守许可协议条款。源代码可在 GitHub 上获取。",
      openSourceLicense:
        "完整许可文本：MIT License — 请查看项目仓库中的 LICENSE 文件。",
      limitationTitle: "6. 责任限制",
      limitationDesc:
        "在任何情况下，开发者或贡献者均不对因使用或无法使用本应用而产生的任何直接、间接、附带、特殊、后果性或惩罚性损害承担责任，即使已被告知此类损害的可能性。这包括但不限于因错误、遗漏、服务中断或财务损失造成的损害。",
      changesTitle: "7. 条款变更",
      changesDesc:
        "我们保留随时修改本使用条款的权利。变更将在本页面发布，并附上更新后的生效日期。变更后继续使用本应用即表示您接受修订后的条款。",
      contactTitle: "8. 联系我们",
      contactDesc:
        "如果您对本使用条款有任何疑问，请在我们的 GitHub 仓库提交 Issue，或联系开发团队。",
      githubLabel: "GitHub 仓库",
      reviewSourceCode: "查看源码验证 →",
    },
    blog: {
      pageTitle: "博客",
      ctaTitle: "试试我们的免费 DeepSeek API 用量仪表盘",
      ctaDesc: "拖入 CSV，立刻看清成本。100% 本地处理，无需注册。",
      ctaButton: "打开仪表盘",
    },
    author: {
      pageTitle: "作者团队",
      pageSubtitle:
        "关于本项目（DeepSeek API 用量分析仪表盘）背后的作者背景、团队信息与更多联系信息。",
      intro:
        "Mindrose 团队由背景各异的成员组成，他们来自不同的大厂，在软件架构、业务分析、在线营销、SEO & GEO 等领域有丰富的经验。",
      profileTitle: "作者简介",
      profileName: "Gavin Chen",
      profileRole: "Solution Architect & Developer",
      profileDesc:
        "Gavin Chen 负责这个项目的产品方向、技术实现与内容策略，并与 MindRose 团队一起完成产品部署、推广和维护。",
      verificationTitle: "更多公开资料",
      teamMembersTitle: "团队成员",
      teamMembersDesc:
        "认识 MindRose 团队背后的核心贡献者与专家，他们共同推动了产品的持续演进。",
      member1Name: "Gavin Chen",
      member1Role: "业务分析 & 系统架构",
      member1Desc:
        "多年BA经验的架构师，专注于业务需求梳理、产品策略规划与系统架构（还有开发）。",
      member2Name: "Lindsay Lin",
      member2Role: "SEO与外贸专家",
      member2Desc:
        "熟悉跨国产品营销策略，有丰富的 SEO 实战经验，负责产品的 SEO & GEO 策略。",
      member3Name: "Angela Lee",
      member3Role: "在线营销专家",
      member3Desc:
        "熟悉在线营销策略、内容创作与分析，帮助产品和服务在获得在线营销推广方面取得成功。",
      member4Name: "Simon L.",
      member4Role: "后端与运维工程师",
      member4Desc:
        "主导各种服务端架构设计、数据库优化及云原生部署。",
      githubLabel: "项目 GitHub 仓库",
      linkedInLabel: "Gavin 的 LinkedIn",
      websiteLabel: "MindRose 官网",
    },
    blogIndex: {
      pageTitle: "博客：我们怎么多快好省地和 DeepSeek 一起成长？",
      pageSubtitle:
        "深度解析 DeepSeek API 使用场景、成本优化、上下文缓存策略、定价对比和开发者工具 —— 由 MindRose 团队原创。",
      article1Title:
        "DeepSeek API 上下文缓存终极指南（2026）",
      article1Desc:
        "了解 DeepSeek 前缀匹配磁盘缓存的运作原理、缓存命中率偏低的原因，以及 5 个提升缓存命中率的 Prompt 工程技巧。",
      article1Tags: "缓存, 成本优化, DeepSeek, Token成本",
      article2Title:
        "Top 5 DeepSeek API 成本优化与可观测性工具横评",
      article2Desc:
        "深度盘点主流 DeepSeek API 监控与优化工具——从实时可观测性平台到隐私优先的 CSV 分析器，全面对比。",
      article2Tags: "工具, 对比, 成本优化, DeepSeek, Token成本",
      article3Title:
        "OpenAI GPT vs Claude vs DeepSeek V4 Pro：开发者成本收益分析",
      article3Desc:
        "硬核 API 定价数据对比——输入成本差距可达 270 倍。分析各模型的经济适用场景，以及如何平滑迁移。",
      article3Tags: "对比, 定价, OpenAI, Claude, GPT, Anthropic",
    },
    costTracker: {
      pageTitle: "DeepSeek API 费用追踪器",
      badge: "免费工具",
      heroTitle: "追踪 DeepSeek API 的每一分钱",
      heroDesc:
        "拖入 DeepSeek 账单 CSV，即刻获取按日、按模型、按 API Key 分类的费用明细 — 所有数据在浏览器本地处理。无需注册，无需上传。",
      cta: "立即分析费用",
      privacyBadge: "100% 隐私 — 数据绝不离开你的浏览器",
      feature1Title: "每日费用明细",
      feature1Desc:
        "通过交互式柱状图精确查看每日支出。一眼发现异常消费和费用尖峰。",
      feature2Title: "按 Key 费用归因",
      feature2Desc:
        "搞清楚到底是哪个 API Key 在吞噬预算。详细到 Key 的表格包含内嵌用量条和一键复制功能。",
      feature3Title: "缓存命中率监控",
      feature3Desc:
        "全面了解上下文缓存为你节省了多少成本。绿色/琥珀色/红色三色标记，让你轻松发现最值得优化的 API Key。",
      feature4Title: "多月对比分析",
      feature4Desc:
        "一次拖入多个 ZIP 文件，自动按月份配对合并。跨账单周期对比消费趋势，追踪你的优化成果。",
      bottomCTA: "准备好掌控 API 成本了吗？",
      bottomCTADesc:
        "无需注册。数据绝不离开浏览器。只需拖拽、放下，Token 去向一目了然。",
      recommendedTools: "推荐工具",
      recommendedDesc:
        "需要实时 API 可观测性？以下工具可与我们的 CSV 分析器互补：",
      recommendedUsingTools: "我们正在使用的好工具",
      recommendedUsingDes:
        "我们正在使用这些工具自己进行开发和部署，好用，就推荐了。",
      useCasesTitle: "典型使用场景",
      useCase1Title: "财务或运营月度复盘",
      useCase1Desc:
        "在核对账单前上传月度导出，快速定位每日费用尖峰、异常归零以及到底是哪几个 Key 推高了支出。",
      useCase2Title: "客户 / 项目分摊结算",
      useCase2Desc:
        "如果一个 DeepSeek 账号服务多个应用或客户，可借助按 Key 与自定义项目视图，把费用回溯到具体内部负责人。",
      useCase3Title: "优化方案回归验证",
      useCase3Desc:
        "改了 Prompt、路由策略或缓存配置后，直接横向比较多个月份，验证这次优化是否真的把成本压下来了。",
      comparisonTitle: "这个工具最适合什么场景",
      comparisonDesc:
        "如果你已经有月度账单 CSV，并希望在零部署、强隐私前提下快速看清成本结构，这一页比重型可观测性方案更合适。",
      comparisonHeaderTool: "方案",
      comparisonHeaderBestFor: "适合场景",
      comparisonHeaderTradeoff: "取舍",
      comparisonRow1Label: "本地 CSV 分析器",
      comparisonRow1BestFor:
        "月度成本复盘、隐私敏感团队、零部署上手",
      comparisonRow1Tradeoff:
        "不是实时监控；依赖导出的账单文件",
      comparisonRow2Label: "API 网关 / 可观测平台",
      comparisonRow2BestFor:
        "实时请求监控、告警、Prompt Trace、团队协作",
      comparisonRow2Tradeoff:
        "通常需要代理接入、供应商配置和持续付费",
      comparisonRow3Label: "手工表格",
      comparisonRow3BestFor:
        "团队很小且数据简单时的临时核对",
      comparisonRow3Tradeoff:
        "维护成本高，缓存可见性弱，长期容易出错",
      faqTitle: "费用追踪常见问题",
      faq1Q: "既然 DeepSeek 后台已经有账单页，为什么还需要 CSV 成本追踪器？",
      faq1A:
        "平台账单页适合导出原始数据，但这个工具会把数据重组为每日趋势、按 Key 归因、缓存命中可见性和项目级汇总，更利于定位问题和复盘。",
      faq2Q: "谁最适合每月看这页？",
      faq2A:
        "通常是负责 Prompt 的工程师、关注 burn rate 的团队负责人，或对账单差异做核对的运营同学。这页就是为这些交接时刻准备的。",
      faq3Q: "它能用于证明一次优化真的有效吗？",
      faq3A:
        "可以。上传两个月或更多月份的数据，对比每日与各 Key 的变化，就能更直观看出 Prompt 改写或缓存优化是否真的降低了成本。",
      backToHome: "返回首页",
    },
    cacheAnalyzer: {
      pageTitle: "DeepSeek 缓存命中率分析器",
      badge: "免费工具",
      heroTitle: "最大化你的 DeepSeek 缓存命中率",
      heroDesc:
        "DeepSeek 上下文缓存可将 API 成本最高削减 90% — 但前提是你得知道自己的命中率。上传 CSV，秒获缓存表现的清晰全景。",
      cta: "分析我的缓存表现",
      privacyBadge: "100% 隐私 — 数据绝不离开你的浏览器",
      cachingExplainerTitle: "DeepSeek 上下文缓存如何工作",
      cachingExplainerDesc:
        "DeepSeek 采用前缀匹配的磁盘缓存机制。如果你的请求开头（前缀）在不同调用中保持一致，后续请求将复用已缓存的计算结果 — 显著降低成本。缓存的稳态前缀相对总输入越长，节省越多。",
      cachingTip1Title: "固定系统提示词",
      cachingTip1Desc:
        "将静态指令放在每次请求的最前面。DeepSeek 从第一个 token 开始缓存；前端任意位置的修改都会使整个缓存失效。",
      cachingTip2Title: "将动态内容放在末尾",
      cachingTip2Desc:
        "组织 Prompt 结构时，将用户问题、时间戳等可变内容放在固定系统提示词和下文之后。这能最大程度扩大可复用的前缀长度。",
      cachingTip3Title: "使用我们的工具监控",
      cachingTip3Desc:
        "每日缓存命中率趋势图 + 各 Key 命中/未命中堆叠柱状图。命中率 > 40%（绿色）表示缓存良好；< 20%（红色）则表示 Prompt 工程还有优化空间。",
      feature1Title: "每日缓存趋势线",
      feature1Desc:
        "持续追踪缓存命中率的变化。某次 Prompt 调整是否拖累了命中率？趋势线一目了然。",
      feature2Title: "各 Key 命中 vs 未命中",
      feature2Desc:
        "每个 API Key 的堆叠柱状图清晰展示计入缓存的 Token（绿色）vs 未命中（灰色），附百分比标签和悬浮提示。",
      benchmarkTitle: "命中率经验基准",
      benchmarkDesc:
        "不同业务的准确数值会有差异，但下面这些实务区间足够用来判断：你的 Prompt 结构是否还留有明显的节流空间。",
      benchmark1Title: "低于 20%",
      benchmark1Desc:
        "通常说明稳定前缀太短，或者可变内容出现在 Prompt 前段，导致可复用部分几乎被打散。",
      benchmark2Title: "20% - 40%",
      benchmark2Desc:
        "属于可用但仍有提升空间的基础线。已经有一定复用，但 Prompt 排布通常还可以继续优化。",
      benchmark3Title: "40% - 60%",
      benchmark3Desc:
        "对很多生产团队来说已经是相当不错的结果，说明静态指令和可复用上下文的组织方式基本合理。",
      benchmark4Title: "60% 以上",
      benchmark4Desc:
        "对于客服、模板化抽取、固定系统提示词加少量用户变量这类重复流程，属于非常优秀的缓存表现。",
      strategyTitle: "更多优化策略",
      strategy1Title: "把稳定上下文与用户输入拆开",
      strategy1Desc:
        "把长期不变的知识、策略块、工具说明组织成可复用前缀，再把用户级别的动态数据追加在后面。",
      strategy2Title: "像发版一样管理 Prompt 版本",
      strategy2Desc:
        "Prompt 前缀的小改动就可能让缓存经济性一夜归零。把 Prompt 修订当成代码发布，并在每次变更后盯紧命中率曲线。",
      strategy3Title: "合并相似流量路径",
      strategy3Desc:
        "如果多个产品共享同一套助手逻辑，尽量统一 Prompt 骨架，让跨请求的可复用前缀保持一致。",
      diagnosisTitle: "命中率突然下滑时检查什么",
      diagnosis1Title: "Prompt 模板变了",
      diagnosis1Desc:
        "前缀改写、指令重排，或在开头插入时间戳，都可能在表面体验不变的情况下大幅拖垮命中率。",
      diagnosis2Title: "流量结构变了",
      diagnosis2Desc:
        "如果一次性任务、长尾查询或新产品流量突然增多，即使代码没回退，前缀复用率也会自然下降。",
      diagnosis3Title: "适合缓存的请求没有稳定路由",
      diagnosis3Desc:
        "逻辑相似的请求若被分散到不同模型、不同 Key 或不同 Prompt 包装层，整体可复用前缀会被切碎。",
      bottomCTATitle: "需要帮助优化 Prompt 缓存策略？",
      bottomCTADesc:
        "MindRose 团队专注于 LLM 架构设计与 Prompt 工程。我们可以帮助你重新设计方案，实现最高的缓存效率。",
      bottomCTALink: "联系我们 →",
      backToHome: "返回首页",
    },
    pricingCalculator: {
      pageTitle: "DeepSeek API 价格计算器",
      badge: "免费工具",
      heroTitle: "即刻估算你的 DeepSeek API 成本",
      heroDesc:
        "对比 DeepSeek V4 Flash、V4 Pro 及竞品模型价格。调整输入/输出 Token 数量和缓存命中率假设，查看真实的成本预估。",
      currencyCNY: "人民币 (CNY)",
      currencyUSD: "美元 (USD)",
      inputTokensLabel: "月输入 Token 量",
      outputTokensLabel: "月输出 Token 量",
      cacheHitRateLabel: "缓存命中率 (%)",
      cacheHitRateHint: "命中率越高，成本越低。DeepSeek 缓存命中按原始输入价格的 12.5% 计费。",
      costEstimateTitle: "预估月度费用",
      deepseekV4Flash: "DeepSeek V4 Flash",
      deepseekV4Pro: "DeepSeek V4 Pro",
      competitorComparison: "竞品定价对比",
      comparisonNote:
        "基于 2026 年 7 月公开发布的 API 定价。实际费用可能因使用模式和缓存效率而有所不同。",
      compModelHeader: "模型",
      compInputPriceHeader: "输入 / 百万 Token",
      compOutputPriceHeader: "输出 / 百万 Token",
      compCacheHitHeader: "缓存命中 / 百万 Token",
      compNotesHeader: "备注",
      compDeepseekV4Flash: "DeepSeek V4 Flash",
      compDeepseekV4Pro: "DeepSeek V4 Pro",
      estimationGuideTitle: "如何估算月用量",
      estimationGuideDesc:
        "如果你手头还没有账单导出，可以先从产品流量倒推：每天请求数、平均 Prompt 长度、平均回复长度，以及预期缓存复用率。",
      estimateStep1Title: "1. 先估算请求量",
      estimateStep1Desc:
        "统计应用在正常一天会发出多少请求，再乘以 30。把活动高峰和日常基线拆开估算更靠谱。",
      estimateStep2Title: "2. 再估算输入 / 输出 Token",
      estimateStep2Desc:
        "挑几组有代表性的 Prompt，估算平均输入和输出 Token。做预算时，稳定的口径往往比极致精确更重要。",
      estimateStep3Title: "3. 最后补上缓存假设",
      estimateStep3Desc:
        "如果系统提示词和上下文复用很高，就用更高的命中率建模；如果每次请求都很独特，就先按接近 0% 估算，把缓存收益当成上行空间。",
      billingModelTitle: "计费模型怎么理解",
      billingModelInputTitle: "未命中的输入 Token",
      billingModelInputDesc:
        "这部分按模型标准输入价计费。当缓存命中率较低时，大 Prompt 往往是总成本的主导项。",
      billingModelCacheTitle: "命中的缓存输入 Token",
      billingModelCacheDesc:
        "当前缀命中历史请求时，DeepSeek 会按更低的缓存命中价格计费，而不是全额输入价格。",
      billingModelOutputTitle: "输出 Token",
      billingModelOutputDesc:
        "模型生成的输出会单独计费。在 Agent 或深度推理场景里，输出成本本身也可能成为主要开销。",
      resultGuideTitle: "如何解读计算结果",
      resultGuide1Title: "高频常规任务优先看 Flash",
      resultGuide1Desc:
        "如果工作负载重复度高、又对延迟敏感，DeepSeek V4 Flash 往往是成本规划的基准下限。",
      resultGuide2Title: "只有质量收益覆盖价差时再上 Pro",
      resultGuide2Desc:
        "关键不在于 Pro 是否更贵，而在于它是否能减少重试、人审和下游错误，从而抵掉这部分价差。",
      resultGuide3Title: "竞品比较要带入你的真实流量结构",
      resultGuide3Desc:
        "列表价格看起来贵的模型，放到特定窄任务里仍可能合理。定栈前请用你自己的 Token 结构再跑一遍计算器。",
      deployCTA: "准备部署你的 AI 技术栈？",
      deployCTADesc:
        "获取免费云额度来运行你的 AI 工作负载。Vultr 为新用户提供 $100 信用金 — 足够托管你的 LLM 代理或分析管线。",
      deployCTALink: "领取 Vultr 免费额度 ($100)",
      backToHome: "返回首页",
    },
    landing: {
      howItWorksTitle: "使用方式",
      howItWorksStep1Title: "1. 导出数据",
      howItWorksStep1Desc:
        "前往 DeepSeek 平台 → 用量 → 导出月度数据。每月下载一个 ZIP 包，内含 amount 和 cost 两个 CSV 文件。",
      howItWorksStep2Title: "2. 拖拽上传",
      howItWorksStep2Desc:
        "将 ZIP 文件（或解压后的 CSV）拖拽到此页面。多个月份文件会自动按文件名配对并合并。",
      howItWorksStep3Title: "3. 查看分析",
      howItWorksStep3Desc:
        "即刻查看费用图表、各 Key 用量明细、缓存命中分析、使用趋势和自定义项目分组 — 所有数据在浏览器本地处理。",
      qaTitle: "常见问题",
      qaQ1: "我的数据会上传到服务器吗？",
      qaA1: "不会。所有 CSV 解析和费用计算均在您的浏览器中完成，数据不会离开您的设备。",
      qaQ2: "我需要上传哪些文件？",
      qaA2: "直接拖拽从 DeepSeek 平台下载的 ZIP 压缩包即可，无需解压。也可以解压后手动上传 amount-*.csv 和 cost-*.csv 文件。",
      qaQ3: "可以同时分析多个月份吗？",
      qaA3: "可以。一次性拖入所有月份的 ZIP（或 CSV）文件，它们会根据文件名自动配对并拼接。",
      qaQ4: "支持哪些模型？",
      qaA4: "DeepSeek 导出中的所有模型均支持。仪表盘会自动检测所有模型，并提供筛选器以便单独或合并查看。",
      qaQ5: "为什么费用显示为 0？",
      qaA5: "需要同时上传同一个月的 amount CSV 和 cost CSV 两个文件。如果缺少其中任何一个，费用数据将无法计算。",
      qaQ6: "显示“上传不完整”是什么意思？",
      qaA6: "表示某个月份只有 amount 文件或只有 cost 文件，缺少另一个。补充缺失的文件并重新上传即可解决。",
      qaQ7: "哪里可以找到更多故障排查帮助？",
      qaA7: "请查看完整操作指南中的“常见问题排查”章节，涵盖了 CSV 格式错误、缓存配置、文件命名规范等常见问题。",
      qaQ8: "有文件大小限制吗？",
      qaA8: "有，单个文件不能超过 50 MB。这是为了防止恶意 ZIP 炸弹导致浏览器卡死。DeepSeek 月度用量导出文件通常小于 1 MB，正常使用不会触发此限制。",
      qaQ9: "可以按自定义项目分组 API Key 吗？",
      qaA9: "可以。切换到「按自定义项目」标签页，点击齿轮图标打开配置面板。将 API Key 从「未分配 Key」区域拖拽到对应的自定义项目分组中即可。项目配置保存在浏览器本地存储中。",
      sisterBadge: "姊妹项目",
      sisterTitle: "你也在用 Agnes API 吗？",
      sisterDesc:
        "如果你还在同时分析 Agnes AI 的成本、模型分布与趋势，可以打开配套的 Agnes AI 专用分析器，继续沿用相同的纯浏览器工作流。",
      sisterVisit: "打开 Agnes AI 分析器",
      sisterRepo: "查看 GitHub 仓库",
      aboutSectionTitle: "关于我们",
      aboutWhyTitle: "为什么开发这个工具？",
      aboutWhyDesc:
        "随着 DeepSeek API 调用的激增，我们发现官方后台导出的 CSV 账单数据难以直观阅读。\n为了搞清楚“到底哪个项目消耗了最多的 Token”以及“缓存命中率如何”，我们决定自己动手，打造一个简单、直观且绝对安全的可视化仪表盘。",
      aboutPrivacyTitle: "极致的隐私与技术架构",
      aboutPrivacyDesc:
        "处理账单数据，隐私是不可妥协的底线。因此，我们采用了纯前端的架构设计。\n基于 Next.js 16 (App Router) 和 React 19，结合 Papa Parse 与 ECharts，所有的 CSV 数据解析和图表渲染 100% 在你的浏览器本地完成。\n没有数据库，你的数据绝不会离开你的设备半步。\n配合 Apple 风格的极简设计和 CSS 自定义属性驱动的双主题，我们希望为你提供最优雅的数据分析体验。",
      aboutMindRoseTitle: "关于 MindRose",
      aboutMindRoseDesc:
        "本项目由 Gavin Chen 及 MindRose 团队开发并开源呈现。MindRose 是专注于为中小制造企业、物流公司及跨国贸易商提供轻量级数字化解决方案的科技团队。\n我们不卖虚无的“数字化转型”概念，而是通过 AI 技术与全栈敏捷开发（Next.js、React、Mendix 等），在几周内为你交付解决实际业务痛点的应用。\n从外贸独立站的 SEO 优化重构，到企业内部核心系统的敏捷搭建，再到 AI Agent 的业务流接入，我们懂技术，更懂你的商业场景。",
      aboutContactTitle: "商业合作",
      aboutContactDesc:
        "想要为你的企业定制类似的数据看板？或者需要将 AI 深度集成到你的业务工作流中？\n或者需要现代优雅的用户交互界面？或者需要多终端的跨部门业务系统？\n或者是基于当前开源项目的进一步合作？",
      aboutContactService:
        "我们提供专业的瓶颈诊断、变革点分析、结合业务的定制化方案、和基于 AI 的开发及运维服务。",
      aboutContactCTA: "联系我们：",
      aboutGitHubLabel: "本项目的 GitHub 仓库",
      aboutLinkedInLabel: "Gavin 的 LinkedIn 主页",
      aboutMindRoseLabel: "MindRose 团队主页",
    },
  },
} as const;

export type Locale = keyof typeof translations;

/** The common shape shared by all translation objects. */
export type TranslationShape = { [K in keyof typeof translations.en]: (typeof translations.en)[K] };

/**
 * Resolve literal string unions (e.g. "DeepSeek Usage" | "DeepSeek 用量")
 * so consuming code doesn't complain about incompatible literal types.
 */
export type TranslationKeys = {
  [K in keyof TranslationShape]: {
    [SK in keyof TranslationShape[K]]: string;
  };
};

export default translations;
